INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, phone, google_maps_url, location, photos, videos, reviews, header_image, header_images, youtube_search, google_place_id, google_rating, google_reviews_count, google_formatted_address, google_phone, google_website, google_business_status, google_types, google_opening_hours, google_photos, google_reviews, google_wheelchair_accessible, breezit_pricing, breezit_rating, breezit_reviews, source) VALUES (
      'sb-058', 'California Ballroom', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $1,323.',
      90, 300,
      1323, 3308, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":1323}'::jsonb, 4.4, 86,
      'breezit'
    ),
(
      'sb-059', 'Forage Kitchen', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $2,756.',
      60, 200,
      2756, 6890, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2756}'::jsonb, 4.55, 115,
      'breezit'
    ),
(
      'sb-060', 'Luxe Cruises & Events', 'South Bay', 'Alameda',
      'Alameda, Alameda County', 'Wedding venue in Alameda, Alameda County. Starting packages from $10,700.',
      66, 220,
      10700, 26750, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10700}'::jsonb, 4.51, 37,
      'breezit'
    ),
(
      'sb-061', 'Claremont Resort & Club', 'South Bay', 'Berkeley',
      'Berkeley, Alameda County', 'Wedding venue in Berkeley, Alameda County. Starting packages from $11,370.',
      94, 312,
      11370, 28425, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":11370}'::jsonb, 4.38, 2423,
      'breezit'
    ),
(
      'sb-062', 'DoubleTree by Hilton Berkeley Marina', 'South Bay', 'Berkeley',
      'Berkeley, Alameda County', 'Wedding venue in Berkeley, Alameda County. Starting packages from $9,528.',
      120, 400,
      9528, 23820, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":9528}'::jsonb, 3.72, 3273,
      'breezit'
    ),
(
      'sb-063', 'Redwood Canyon by Wedgewood Weddings', 'South Bay', 'Castro Valley',
      'Castro Valley, Alameda County', 'Wedding venue in Castro Valley, Alameda County. Starting packages from $6,760.',
      90, 300,
      6760, 16900, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6760}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-064', 'Piedmont Community Hall', 'South Bay', 'Piedmont',
      'Piedmont, Alameda County', 'Wedding venue in Piedmont, Alameda County. Starting packages from $5,366.',
      96, 320,
      5366, 13415, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5366}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-065', 'Berkeley City Club', 'South Bay', 'Berkeley',
      'Berkeley, Alameda County', 'Wedding venue in Berkeley, Alameda County. Starting packages from $10,260.',
      60, 200,
      10260, 25650, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10260}'::jsonb, 4.37, 777,
      'breezit'
    ),
(
      'sb-066', 'UC Botanical Garden', 'South Bay', 'Berkeley',
      'Berkeley, Alameda County', 'Wedding venue in Berkeley, Alameda County. Starting packages from $8,085.',
      22, 72,
      8085, 20213, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8085}'::jsonb, 4.8, 1955,
      'breezit'
    ),
(
      'sb-067', 'Piedmont Community church and Guild Hall', 'South Bay', 'Piedmont',
      'Piedmont, Alameda County', 'Wedding venue in Piedmont, Alameda County. Starting packages from $5,816.',
      90, 300,
      5816, 14540, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5816}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-068', 'The Little Kitchen by Jessica Lasky', 'South Bay', 'Berkeley',
      'Berkeley, Alameda County', 'Wedding venue in Berkeley, Alameda County. Starting packages from $12,403.',
      23, 75,
      12403, 31008, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":12403}'::jsonb, 4.7, 12,
      'breezit'
    ),
(
      'sb-069', 'el PRADO', 'South Bay', 'Cupertino',
      'Cupertino, Santa Clara County', 'Wedding venue in Cupertino, Santa Clara County. Starting packages from $20,297.',
      75, 250,
      20297, 50743, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":20297}'::jsonb, 4.21, 1495,
      'breezit'
    ),
(
      'sb-070', 'Graduate Palo Alto', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $27,064.',
      30, 100,
      27064, 67660, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":27064}'::jsonb, 4.02, 127,
      'breezit'
    ),
(
      'sb-071', 'Woman''s Club Palo Alto', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $4,911.',
      45, 150,
      4911, 12278, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":4911}'::jsonb, 4.6, 77,
      'breezit'
    ),
(
      'sb-072', 'Palo Alto Hills Golf And Country Club', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $26,628.',
      30, 100,
      26628, 66570, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":26628}'::jsonb, 4.55, 293,
      'breezit'
    ),
(
      'sb-073', 'Sheraton Palo Alto', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $13,325.',
      45, 150,
      13325, 33313, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":13325}'::jsonb, 3.94, 2304,
      'breezit'
    ),
(
      'sb-074', 'Crowne Plaza - Palo Alto', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $10,518.',
      180, 600,
      10518, 26295, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10518}'::jsonb, 4.1, 1652,
      'breezit'
    ),
(
      'sb-075', 'Oshman Family JCC', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $6,384.',
      114, 380,
      6384, 15960, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6384}'::jsonb, 3.86, 342,
      'breezit'
    ),
(
      'sb-076', 'Mitchell Park Community Center', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $1,903.',
      75, 250,
      1903, 4758, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":1903}'::jsonb, 4.6, 184,
      'breezit'
    ),
(
      'sb-077', 'The Sea by Alexander''s Steakhouse', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $18,792.',
      45, 150,
      18792, 46980, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":18792}'::jsonb, 4.3, 2624,
      'breezit'
    ),
(
      'sb-078', 'Harmony Hall & Courtyard', 'South Bay', 'Palo Alto',
      'Palo Alto, Santa Clara County', 'Wedding venue in Palo Alto, Santa Clara County. Starting packages from $2,728.',
      69, 230,
      2728, 6820, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2728}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-079', 'Toll House Hotel', 'South Bay', 'Los Gatos',
      'Los Gatos, Santa Clara County', 'Wedding venue in Los Gatos, Santa Clara County. Starting packages from $10,186.',
      60, 200,
      10186, 25465, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10186}'::jsonb, 4.15, 850,
      'breezit'
    ),
(
      'sb-080', 'Cucina Venti', 'South Bay', 'Mountain View',
      'Mountain View, Santa Clara County', 'Wedding venue in Mountain View, Santa Clara County. Starting packages from $16,367.',
      30, 100,
      16367, 40918, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":16367}'::jsonb, 4.2, 1711,
      'breezit'
    ),
(
      'sb-081', 'Juniper Cupertino, Curio Collection by Hilton', 'South Bay', 'Cupertino',
      'Cupertino, Santa Clara County', 'Wedding venue in Cupertino, Santa Clara County. Starting packages from $7,843.',
      60, 200,
      7843, 19608, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":7843}'::jsonb, 4.21, 1495,
      'breezit'
    ),
(
      'pen-047', 'Hastings House Garden Weddings', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $4,922.',
      15, 50,
      4922, 12305, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":4922}'::jsonb, 4.97, 112,
      'breezit'
    ),
(
      'pen-048', 'Sam''s Chowder House Half Moon Bay', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $6,563.',
      36, 120,
      6563, 16408, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6563}'::jsonb, 4.4, 8153,
      'breezit'
    ),
(
      'pen-049', 'La Nebbia Winery', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $9,291.',
      30, 100,
      9291, 23228, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":9291}'::jsonb, 3.84, 352,
      'breezit'
    ),
(
      'pen-050', 'Long Branch Saloon and Farms', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $10,963.',
      90, 300,
      10963, 27408, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10963}'::jsonb, 4.75, 84,
      'breezit'
    ),
(
      'pen-051', 'San Benito House', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $8,400.',
      60, 200,
      8400, 21000, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8400}'::jsonb, 4.59, 468,
      'breezit'
    ),
(
      'pen-052', 'Fattoria E Mare', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $9,316.',
      30, 100,
      9316, 23290, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":9316}'::jsonb, 4.16, 730,
      'breezit'
    ),
(
      'pen-053', 'Lisbeth Mozo', 'Peninsula', 'Half Moon Bay',
      'Half Moon Bay, San Mateo County', 'Wedding venue in Half Moon Bay, San Mateo County. Starting packages from $11,250.',
      75, 250,
      11250, 28125, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":11250}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'pen-054', 'Four Seasons Hotel Silicon Valley', 'Peninsula', 'East Palo Alto',
      'East Palo Alto, San Mateo County', 'Wedding venue in East Palo Alto, San Mateo County. Starting packages from $29,304.',
      75, 250,
      29304, 73260, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":29304}'::jsonb, 4.58, 1835,
      'breezit'
    ),
(
      'pen-055', 'Grand Bay San Francisco', 'Peninsula', 'Redwood City',
      'Redwood City, San Mateo County', 'Wedding venue in Redwood City, San Mateo County. Starting packages from $27,408.',
      120, 400,
      27408, 68520, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":27408}'::jsonb, 4.08, 2141,
      'breezit'
    ),
(
      'pen-056', 'Costanoa Coastal Lodge', 'Peninsula', 'Pescadero',
      'Pescadero, San Mateo County', 'Wedding venue in Pescadero, San Mateo County. Starting packages from $8,641.',
      129, 430,
      8641, 21603, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8641}'::jsonb, 4.28, 87,
      'breezit'
    ),
(
      'pen-057', 'San Francisco Airport Marriott Waterfront', 'Peninsula', 'Burlingame',
      'Burlingame, San Mateo County', 'Wedding venue in Burlingame, San Mateo County. Starting packages from $5,181.',
      300, 1000,
      5181, 12953, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5181}'::jsonb, 4.2, 4059,
      'breezit'
    ),
(
      'pen-058', 'Fairview Crystal Springs', 'Peninsula', 'Burlingame',
      'Burlingame, San Mateo County', 'Wedding venue in Burlingame, San Mateo County. Starting packages from $6,487.',
      84, 280,
      6487, 16218, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6487}'::jsonb, 4.08, 143,
      'breezit'
    ),
(
      'pen-059', 'Cafe Wisteria', 'Peninsula', 'Menlo Park',
      'Menlo Park, San Mateo County', 'Wedding venue in Menlo Park, San Mateo County. Starting packages from $19,182.',
      50, 165,
      19182, 47955, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":19182}'::jsonb, 4.23, 229,
      'breezit'
    ),
(
      'pen-060', 'The Alexandria at San Carlos', 'Peninsula', 'San Carlos',
      'San Carlos, San Mateo County', 'Wedding venue in San Carlos, San Mateo County. Starting packages from $20,509.',
      90, 300,
      20509, 51273, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":20509}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'pen-061', 'Dominic’s at Oyster Point', 'Peninsula', 'South San Francisco',
      'South San Francisco, San Mateo County', 'Wedding venue in South San Francisco, San Mateo County. Starting packages from $5,245.',
      45, 150,
      5245, 13113, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5245}'::jsonb, 4.52, 201,
      'breezit'
    ),
(
      'mon-019', 'Glen Oaks Big Sur', 'Monterey', 'Big Sur',
      'Big Sur, Monterey County', 'Wedding venue in Big Sur, Monterey County. Starting packages from $7,111.',
      30, 100,
      7111, 17778, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":7111}'::jsonb, 4.2, 568,
      'breezit'
    ),
(
      'mon-020', 'COAST Big Sur', 'Monterey', 'Big Sur',
      'Big Sur, Monterey County', 'Wedding venue in Big Sur, Monterey County. Starting packages from $11,206.',
      15, 50,
      11206, 28015, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":11206}'::jsonb, 4.46, 728,
      'breezit'
    ),
(
      'mon-021', 'Loma Vista Gardens', 'Monterey', 'Big Sur',
      'Big Sur, Monterey County', 'Wedding venue in Big Sur, Monterey County. Starting packages from $19,136.',
      63, 210,
      19136, 47840, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":19136}'::jsonb, 4.71, 49,
      'breezit'
    ),
(
      'mon-022', 'COAST Big Sur: Henry Miller Gallery', 'Monterey', 'Big Sur',
      'Big Sur, Monterey County', 'Wedding venue in Big Sur, Monterey County. Starting packages from $8,405.',
      7, 24,
      8405, 21013, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8405}'::jsonb, 4.46, 728,
      'breezit'
    ),
(
      'mon-023', 'The Village Big Sur', 'Monterey', 'Big Sur',
      'Big Sur, Monterey County', 'Wedding venue in Big Sur, Monterey County. Starting packages from $30,170.',
      45, 150,
      30170, 75425, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":30170}'::jsonb, 4.75, 65,
      'breezit'
    ),
(
      'mon-024', 'The Perry House', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $16,794.',
      42, 140,
      16794, 41985, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":16794}'::jsonb, 4.84, 290,
      'breezit'
    ),
(
      'mon-025', 'Monterey Beach Hotel', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $10,584.',
      96, 320,
      10584, 26460, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10584}'::jsonb, 4.59, 19,
      'breezit'
    ),
(
      'mon-026', 'The Club at Pasadera', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $39,803.',
      90, 300,
      39803, 99508, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":39803}'::jsonb, 4.44, 227,
      'breezit'
    ),
(
      'mon-027', 'Tarpy''s Roadhouse', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $5,265.',
      21, 70,
      5265, 13163, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5265}'::jsonb, 4.5, 1876,
      'breezit'
    ),
(
      'mon-028', 'De Tierra Events', 'Monterey', 'Salinas',
      'Salinas, Monterey County', 'Wedding venue in Salinas, Monterey County. Starting packages from $18,026.',
      10, 32,
      18026, 45065, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":18026}'::jsonb, 4.44, 16,
      'breezit'
    ),
(
      'mon-029', 'Point Pinos Grill', 'Monterey', 'Pacific Grove',
      'Pacific Grove, Monterey County', 'Wedding venue in Pacific Grove, Monterey County. Starting packages from $12,555.',
      30, 100,
      12555, 31388, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":12555}'::jsonb, 4.39, 453,
      'breezit'
    ) ON CONFLICT (id) DO NOTHING;