INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, google_maps_url, location, google_place_id, google_rating, google_reviews_count, source) VALUES
  ('pen-039', 'The Marker San Francisco', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $12,460.', 60, 200, 12460, 31150, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-040', 'City View At Metreon', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $24,782.', 150, 500, 24782, 61955, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-041', 'Wayfare Tavern', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $33,131.', 15, 50, 33131, 82828, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-042', 'Julia Morgan Ballroom at the Merchants Exchange', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $32,589.', 150, 500, 32589, 81473, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-043', 'Presidio Chapel by Wedgewood Weddings', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $13,246.', 45, 150, 13246, 33115, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-044', 'The Walt Disney Family Museum', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $8,690.', 39, 130, 8690, 21725, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-045', 'Legion of Honor', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $10,863.', 129, 430, 10863, 27158, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-037', 'Palm Springs Club', 'North Bay', 'Palm Springs', 'Palm Springs, Riverside County', 'Wedding venue in Palm Springs, Riverside County. Starting packages from $1,052.', 15, 50, 1052, 2630, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-038', 'Monte Verde Inn', 'North Bay', 'Foresthill', 'Foresthill, Placer County', 'Wedding venue in Foresthill, Placer County. Starting packages from $8,044.', 66, 220, 8044, 20110, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-039', 'Olivas Adobe', 'North Bay', 'Ventura', 'Ventura, Ventura County', 'Wedding venue in Ventura, Ventura County. Starting packages from $474.', 60, 200, 474, 1185, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration')
ON CONFLICT (id) DO NOTHING;