INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, phone, google_maps_url, location, photos, videos, reviews, header_image, header_images, youtube_search, google_place_id, google_rating, google_reviews_count, google_formatted_address, google_phone, google_website, google_business_status, google_types, google_opening_hours, google_photos, google_reviews, google_wheelchair_accessible, breezit_pricing, breezit_rating, breezit_reviews, source) VALUES (
      'nb-040', 'Calico Ghost Town', 'North Bay', 'Yermo',
      'Yermo, San Bernardino County', 'Wedding venue in Yermo, San Bernardino County. Starting packages from $2,155.',
      30, 100,
      2155, 5388, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2155}'::jsonb, 4.11, 1110,
      'breezit'
    ),
(
      'nb-041', 'Serra Cross Park', 'North Bay', 'Ventura',
      'Ventura, Ventura County', 'Wedding venue in Ventura, Ventura County. Starting packages from $644.',
      90, 300,
      644, 1610, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":644}'::jsonb, 4.8, 980,
      'breezit'
    ),
(
      'nb-042', 'Mission Basilica San Buenaventura', 'North Bay', 'Ventura',
      'Ventura, Ventura County', 'Wedding venue in Ventura, Ventura County. Starting packages from $6,221.',
      90, 300,
      6221, 15553, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6221}'::jsonb, 4.65, 1396,
      'breezit'
    ),
(
      'sb-024', 'Joseph D. Grant County Park', 'South Bay', 'Mount Hamilton',
      'Mount Hamilton, Santa Clara County', 'Wedding venue in Mount Hamilton, Santa Clara County. Starting packages from $371.',
      120, 400,
      371, 928, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":371}'::jsonb, 4.6, 1066,
      'breezit'
    ),
(
      'sb-025', 'Mt. Madonna County Park', 'South Bay', 'Watsonville',
      'Watsonville, Santa Clara County', 'Wedding venue in Watsonville, Santa Clara County. Starting packages from $514.',
      45, 150,
      514, 1285, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":514}'::jsonb, 4.8, 743,
      'breezit'
    ),
(
      'sb-026', 'Sanborn County Park', 'South Bay', 'Saratoga',
      'Saratoga, Santa Clara County', 'Wedding venue in Saratoga, Santa Clara County. Starting packages from $513.',
      60, 200,
      513, 1283, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":513}'::jsonb, 4.7, 2319,
      'breezit'
    ),
(
      'nb-043', 'Rustic Root - Gaslamp', 'North Bay', 'San Diego',
      'San Diego, San Diego County', 'Wedding venue in San Diego, San Diego County. Starting packages from $11,448.',
      63, 210,
      11448, 28620, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":11448}'::jsonb, 4.4, 2729,
      'breezit'
    ),
(
      'nb-044', 'The Gables Wine Country Inn', 'North Bay', 'Santa Rosa',
      'Santa Rosa, Sonoma County', 'Wedding venue in Santa Rosa, Sonoma County. Starting packages from $1,628.',
      15, 50,
      1628, 4070, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":1628}'::jsonb, 4.6, 139,
      'breezit'
    ),
(
      'nb-045', 'ST Helena French Farmhouse', 'North Bay', 'Santa Rosa',
      'Santa Rosa, Sonoma County', 'Wedding venue in Santa Rosa, Sonoma County. Starting packages from $19,673.',
      30, 100,
      19673, 49183, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":19673}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'nb-046', 'Korean Bell', 'North Bay', 'Los Angeles',
      'Los Angeles, Los Angeles County', 'Wedding venue in Los Angeles, Los Angeles County. Starting packages from $627.',
      45, 150,
      627, 1568, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":627}'::jsonb, 4.79, 7200,
      'breezit'
    ),
(
      'nb-047', 'JEH Ranch', 'North Bay', 'Bakersfield',
      'Bakersfield, Kern County', 'Wedding venue in Bakersfield, Kern County. Starting packages from $10,100.',
      75, 250,
      10100, 25250, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10100}'::jsonb, 3.38, 14,
      'breezit'
    ),
(
      'pen-046', 'Hyatt Regency San Francisco Airport', 'Peninsula', 'Burlingame',
      'Burlingame, San Mateo County', 'Wedding venue in Burlingame, San Mateo County. Starting packages from $6,961.',
      30, 100,
      6961, 17403, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6961}'::jsonb, 4.15, 5407,
      'breezit'
    ),
(
      'nb-048', 'The Dalya Estate', 'North Bay', 'Sebastopol',
      'Sebastopol, Sonoma County', 'Wedding venue in Sebastopol, Sonoma County. Starting packages from $16,275.',
      33, 110,
      16275, 40688, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":16275}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'nb-049', 'Thorn Hill Vineyards', 'North Bay', 'Lower Lake',
      'Lower Lake, Lake County', 'Wedding venue in Lower Lake, Lake County. Starting packages from $4,290.',
      23, 75,
      4290, 10725, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":4290}'::jsonb, 4.48, 67,
      'breezit'
    ),
(
      'sc-019', 'Valencia Hall', 'Santa Cruz', 'Aptos',
      'Aptos, Santa Cruz County', 'Wedding venue in Aptos, Santa Cruz County. Starting packages from $688.',
      24, 80,
      688, 1720, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":688}'::jsonb, 4.81, 27,
      'breezit'
    ),
(
      'sc-020', 'Quail Hollow Ranch and Full Lawn', 'Santa Cruz', 'Felton',
      'Felton, Santa Cruz County', 'Wedding venue in Felton, Santa Cruz County. Starting packages from $1,062.',
      30, 100,
      1062, 2655, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":1062}'::jsonb, 4.7, 261,
      'breezit'
    ),
(
      'sc-021', 'Aptos Village Park Clubhouse and 1⁄3 Lawn', 'Santa Cruz', 'Aptos',
      'Aptos, Santa Cruz County', 'Wedding venue in Aptos, Santa Cruz County. Starting packages from $1,934.',
      60, 200,
      1934, 4835, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":1934}'::jsonb, 4.52, 173,
      'breezit'
    ),
(
      'nb-050', 'Robledo Barn', 'North Bay', 'Sonoma',
      'Sonoma, Sonoma County', 'Wedding venue in Sonoma, Sonoma County. Starting packages from $5,463.',
      75, 250,
      5463, 13658, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5463}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'nb-051', 'ABC Ranch', 'North Bay', 'Thermal',
      'Thermal, Riverside County', 'Wedding venue in Thermal, Riverside County. Starting packages from $11,636.',
      30, 100,
      11636, 29090, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":11636}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-027', 'The Ranch at Silver Creek by Wedgewood Weddings', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $10,802.',
      90, 300,
      10802, 27005, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10802}'::jsonb, 4.2, 59,
      'breezit'
    ),
(
      'sb-028', 'Hayes Mansion San Jose, Curio Collection by Hilton', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $13,672.',
      150, 500,
      13672, 34180, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":13672}'::jsonb, 4.22, 2299,
      'breezit'
    ),
(
      'sb-029', 'Blanco Urban Venue', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $8,007.',
      69, 230,
      8007, 20018, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8007}'::jsonb, 4.74, 56,
      'breezit'
    ),
(
      'sb-030', 'Cathedral Basilica of St. Joseph', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $2,198.',
      90, 300,
      2198, 5495, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2198}'::jsonb, 4.7, 937,
      'breezit'
    ),
(
      'sb-031', 'California Theater', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $13,344.',
      84, 280,
      13344, 33360, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":13344}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-032', 'GrandView San Jose', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $20,636.',
      60, 200,
      20636, 51590, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":20636}'::jsonb, 4.07, 3734,
      'breezit'
    ),
(
      'sb-033', 'Signia by Hilton San Jose', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $6,876.',
      360, 1200,
      6876, 17190, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6876}'::jsonb, 4.01, 450,
      'breezit'
    ),
(
      'sb-034', 'Courtyard by Marriott San Jose/Silicon Valley', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $3,938.',
      45, 150,
      3938, 9845, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":3938}'::jsonb, 4.32, 719,
      'breezit'
    ),
(
      'sb-035', 'Santa Teresa Golf Club', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $2,357.',
      39, 130,
      2357, 5893, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2357}'::jsonb, 3.95, 445,
      'breezit'
    ),
(
      'sb-036', 'Napredak Hall', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $8,750.',
      105, 350,
      8750, 21875, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8750}'::jsonb, 4.1, 137,
      'breezit'
    ),
(
      'sb-037', 'San Jose Woman''s Club', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $2,734.',
      60, 200,
      2734, 6835, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2734}'::jsonb, 4.39, 145,
      'breezit'
    ),
(
      'sb-038', 'Wilcox Manor', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $3,544.',
      60, 200,
      3544, 8860, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":3544}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-039', 'SP2 Communal Bar + Restaurant', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $56,440.',
      36, 120,
      56440, 141100, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":56440}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-040', 'Winchester Mystery House', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $11,786.',
      60, 200,
      11786, 29465, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":11786}'::jsonb, 4.36, 16008,
      'breezit'
    ),
(
      'sb-041', 'Mt Hamilton Grandview Restaurant and Venue', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $20,669.',
      60, 200,
      20669, 51673, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":20669}'::jsonb, 4.07, 3708,
      'breezit'
    ),
(
      'sb-042', 'The Tech Interactive', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $5,500.',
      180, 600,
      5500, 13750, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":5500}'::jsonb, NULL, NULL,
      'breezit'
    ),
(
      'sb-043', 'San Jose Country Club', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $13,313.',
      68, 225,
      13313, 33283, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":13313}'::jsonb, 4.44, 239,
      'breezit'
    ),
(
      'sb-044', 'La Foret', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $22,006.',
      45, 150,
      22006, 55015, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":22006}'::jsonb, 4.25, 1383,
      'breezit'
    ),
(
      'sb-045', 'Friendship Banquet Hall', 'South Bay', 'San Jose',
      'San Jose, Santa Clara County', 'Wedding venue in San Jose, Santa Clara County. Starting packages from $23,408.',
      60, 200,
      23408, 58520, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":23408}'::jsonb, 4.2, 59,
      'breezit'
    ),
(
      'sb-046', 'Fairview Metropolitan', 'South Bay', 'Berkeley',
      'Berkeley, Alameda County', 'Wedding venue in Berkeley, Alameda County. Starting packages from $12,436.',
      68, 225,
      12436, 31090, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":12436}'::jsonb, 4.7, 12,
      'breezit'
    ),
(
      'sb-047', 'Kissel Uptown Oakland', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $20,672.',
      60, 200,
      20672, 51680, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":20672}'::jsonb, 4.2, 206,
      'breezit'
    ),
(
      'sb-048', 'Dunsmuir Hellman Historical Estate', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $1,703.',
      60, 200,
      1703, 4258, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":1703}'::jsonb, 4.5, 127,
      'breezit'
    ),
(
      'sb-049', 'Skyline UCC Church', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $2,431.',
      60, 200,
      2431, 6078, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":2431}'::jsonb, 4.58, 62,
      'breezit'
    ),
(
      'sb-050', 'Oakland Zoo', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $7,235.',
      38, 125,
      7235, 18088, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":7235}'::jsonb, 4.6, 12901,
      'breezit'
    ),
(
      'sb-051', 'Sequoyah Country Club', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $8,864.',
      90, 300,
      8864, 22160, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":8864}'::jsonb, 4.55, 332,
      'breezit'
    ),
(
      'sb-052', 'Preservation Park', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $6,284.',
      90, 300,
      6284, 15710, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":6284}'::jsonb, 4.51, 287,
      'breezit'
    ),
(
      'sb-053', 'Children''s Fairyland', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $9,426.',
      45, 150,
      9426, 23565, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":9426}'::jsonb, 4.5, 1393,
      'breezit'
    ),
(
      'sb-054', 'Pizzaiolo', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $35,831.',
      27, 90,
      35831, 89578, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":35831}'::jsonb, 4.5, 775,
      'breezit'
    ),
(
      'sb-055', 'Diamond Banquet Hall & Catering', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $10,474.',
      105, 350,
      10474, 26185, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":10474}'::jsonb, 4.4, 76,
      'breezit'
    ),
(
      'sb-056', 'The Oakland Scottish Rite Center', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $13,230.',
      180, 600,
      13230, 33075, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":13230}'::jsonb, 4.6, 344,
      'breezit'
    ),
(
      'sb-057', 'Temescal Beach House', 'South Bay', 'Oakland',
      'Oakland, Alameda County', 'Wedding venue in Oakland, Alameda County. Starting packages from $7,814.',
      24, 80,
      7814, 19535, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":7814}'::jsonb, 4.59, 106,
      'breezit'
    ) ON CONFLICT (id) DO NOTHING;