INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, google_maps_url, location, google_place_id, google_rating, google_reviews_count, source) VALUES
  ('mon-018', 'California Seltzer Co.', 'Monterey', 'Pacific Grove', 'Pacific Grove, Monterey County', 'Wedding venue in Pacific Grove, Monterey County. Starting packages from $2,731.', 45, 150, 2731, 6828, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-025', 'Pacheco Ranch Winery', 'North Bay', 'Novato', 'Novato, Marin County', 'Wedding venue in Novato, Marin County. Starting packages from $4,500.', 60, 200, 4500, 11250, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-026', 'North Tahoe Event Center', 'North Bay', 'Kings Beach', 'Kings Beach, Placer County', 'Wedding venue in Kings Beach, Placer County. Starting packages from $4,950.', 120, 400, 4950, 12375, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-027', 'Sierra Cider', 'North Bay', 'Mariposa', 'Mariposa, Mariposa County', 'Wedding venue in Mariposa, Mariposa County. Starting packages from $2,000.', 90, 300, 2000, 5000, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-028', 'St. Francis Winery', 'North Bay', 'Santa Rosa', 'Santa Rosa, Sonoma County', 'Wedding venue in Santa Rosa, Sonoma County. Starting packages from $7,000.', 60, 200, 7000, 17500, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-029', 'Merryvale Vineyards', 'North Bay', NULL, NULL, 'Wedding venue in California. Starting packages from $17,944.', 30, 100, 17944, 44860, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-022', 'Golden Gate Club at The Presidio', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $14,240.', 66, 220, 14240, 35600, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-023', 'Venture Retreat Center', 'Peninsula', 'Pescadero', 'Pescadero, San Mateo County', 'Wedding venue in Pescadero, San Mateo County. Starting packages from $6,800.', 45, 150, 6800, 17000, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-030', 'Sea Ranch Lodge', 'North Bay', 'Sea Ranch', 'Sea Ranch, Sonoma County', 'Wedding venue in Sea Ranch, Sonoma County. Starting packages from $45,773.', 33, 110, 45773, 114433, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-031', 'Sonoma Coast Villa', 'North Bay', 'Bodega', 'Bodega, Sonoma County', 'Wedding venue in Bodega, Sonoma County. Starting packages from $4,000.', 30, 100, 4000, 10000, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration')
ON CONFLICT (id) DO NOTHING;