INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, phone, google_maps_url, location, photos, videos, reviews, header_image, header_images, youtube_search, google_place_id, google_rating, google_reviews_count, google_formatted_address, google_phone, google_website, google_business_status, google_types, google_opening_hours, google_photos, google_reviews, google_wheelchair_accessible, breezit_pricing, breezit_rating, breezit_reviews, source) VALUES (
      'mon-030', 'Intercontinental The Clement Monterey', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $32,864.',
      60, 200,
      32864, 82160, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":32864}'::jsonb, 4.34, 3324,
      'breezit'
    ),
(
      'mon-031', 'Wave Street Studios', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $7,150.',
      45, 150,
      7150, 17875, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":7150}'::jsonb, 4.7, 81,
      'breezit'
    ),
(
      'mon-032', 'Old Monterey Inn', 'Monterey', 'Monterey',
      'Monterey, Monterey County', 'Wedding venue in Monterey, Monterey County. Starting packages from $13,929.',
      12, 40,
      13929, 34823, 'starting_package',
      NULL, NULL, NULL,
      NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL, NULL,
      NULL,
      '{"source":"breezit.com","starting_from":13929}'::jsonb, 4.61, 286,
      'breezit'
    ) ON CONFLICT (id) DO NOTHING;