INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, google_maps_url, location, google_place_id, google_rating, google_reviews_count, source) VALUES
  ('pen-029', 'Bay Lights Charters', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $8,581.', 15, 49, 8581, 21453, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-030', 'James Leary Flood Mansion', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $16,019.', 50, 165, 16019, 40048, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-031', 'San Francisco City Hall', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $10,863.', 900, 3000, 10863, 27158, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-032', 'The Olympic Club', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $12,763.', 90, 300, 12763, 31908, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-033', 'Fairmont San Francisco', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $10,523.', 105, 350, 10523, 26308, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-034', 'SF Museum of Modern Art', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $8,690.', 180, 600, 8690, 21725, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-035', 'The University Club of San Francisco', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $17,360.', 45, 150, 17360, 43400, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-036', 'The Westin St. Francis', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $21,725.', 225, 750, 21725, 54313, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-037', 'Marines Memorial Club & Hotel', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $10,933.', 81, 270, 10933, 27333, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-038', 'Bimbo''s 365 Club', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $36,777.', 135, 450, 36777, 91943, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration')
ON CONFLICT (id) DO NOTHING;