INSERT INTO venues (id, name, region, subregion, address, description, capacity_min, capacity_max, price_min, price_max, price_unit, website, google_maps_url, location, google_place_id, google_rating, google_reviews_count, source) VALUES
  ('pen-024', 'The Hibernia', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $41,712.', 225, 750, 41712, 104280, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-032', 'Winchester Estate by Wedgewood Weddings', 'North Bay', 'Meadow Vista', 'Meadow Vista, Placer County', 'Wedding venue in Meadow Vista, Placer County. Starting packages from $7,713.', 45, 150, 7713, 19283, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-033', 'Sterling Hotel by Wedgewood Weddings', 'North Bay', 'Sacramento', 'Sacramento, Sacramento County', 'Wedding venue in Sacramento, Sacramento County. Starting packages from $6,826.', 60, 200, 6826, 17065, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-034', 'San Ramon Waters by Wedgewood Weddings', 'North Bay', 'San Ramon', 'San Ramon, Contra Costa County', 'Wedding venue in San Ramon, Contra Costa County. Starting packages from $6,760.', 75, 250, 6760, 16900, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-035', 'Jefferson Street Mansion by Wedgewood Weddings', 'North Bay', 'Benicia', 'Benicia, Solano County', 'Wedding venue in Benicia, Solano County. Starting packages from $6,604.', 60, 200, 6604, 16510, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('nb-036', 'Stonetree Estate by Wedgewood Weddings', 'North Bay', 'Novato', 'Novato, Marin County', 'Wedding venue in Novato, Marin County. Starting packages from $8,664.', 60, 200, 8664, 21660, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-025', 'The Pearl', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $9,503.', 144, 480, 9503, 23758, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-026', 'Log Cabin at the Presidio', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $10,927.', 36, 120, 10927, 27318, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-027', 'Chambers eat + drink', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $26,070.', 45, 150, 26070, 65175, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration'),
  ('pen-028', 'Beacon Grand, A Union Square Hotel', 'Peninsula', 'San Francisco', 'San Francisco, San Francisco County', 'Wedding venue in San Francisco, San Francisco County. Starting packages from $22,226.', 60, 200, 22226, 55565, 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, 'json_migration')
ON CONFLICT (id) DO NOTHING;